name: catchlog_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.1.5
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.0.1
  timezone: ^0.9.2
  syncfusion_flutter_charts: ^22.2.10
  path_provider: ^2.0.15
  open_file: ^3.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
