name: catchlog_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4

  # Firebase packages - upgraded & aligned
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  google_sign_in: ^7.1.1
  fl_chart: ^0.70.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_local_notifications: ^19.4.1
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  intl: ^0.20.0
  csv: ^6.0.0
  share_plus: ^11.1.0
  cross_file: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
