// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDx0z22-iBWtQqgpcKbpN_sx3zfOXHXM',
    appId: '1:212499320072:web:e82d7e8d5ddb2401d1b0bd',
    messagingSenderId: '212499320072',
    projectId: 'samaki-app-5988d',
    authDomain: 'samaki-app-5988d.firebaseapp.com',
    storageBucket: 'samaki-app-5988d.firebasestorage.app',
    measurementId: 'G-HLGJ44R14J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrW5dkWVVpBePU9-h-1TiXywnkRU1Q3i4',
    appId: '1:212499320072:android:cecaae60783ef929d1b0bd',
    messagingSenderId: '212499320072',
    projectId: 'samaki-app-5988d',
    storageBucket: 'samaki-app-5988d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-yMlhFo5k10SLjiykOC4YqRKvdAnB5M',
    appId: '1:212499320072:ios:2346b0494b2a25d5d1b0bd',
    messagingSenderId: '212499320072',
    projectId: 'samaki-app-5988d',
    storageBucket: 'samaki-app-5988d.firebasestorage.app',
    iosBundleId: 'com.example.catchlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-yMlhFo5k10SLjiykOC4YqRKvdAnB5M',
    appId: '1:212499320072:ios:2346b0494b2a25d5d1b0bd',
    messagingSenderId: '212499320072',
    projectId: 'samaki-app-5988d',
    storageBucket: 'samaki-app-5988d.firebasestorage.app',
    iosBundleId: 'com.example.catchlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDx0z22-iBWtQqgpcKbpN_sx3zfOXHXM',
    appId: '1:212499320072:web:3bdfe293ca3443dfd1b0bd',
    messagingSenderId: '212499320072',
    projectId: 'samaki-app-5988d',
    authDomain: 'samaki-app-5988d.firebaseapp.com',
    storageBucket: 'samaki-app-5988d.firebasestorage.app',
    measurementId: 'G-L52MD894E4',
  );
}
